DROP SEQUENCE BNOSEQ;
DROP TABLE MBOARD;

CREATE SEQUENCE BNOSEQ;

CREATE TABLE MBOARD(
	BNO NUMBER PRIMARY KEY,
	BNAME VARCHAR2(500) NOT NULL,
	BTITLE VARCHAR2(1000) NOT NULL,
	BCONTENT VARCHAR2(4000) NOT NULL,
	BDATE DATE NOT NULL
);

INSERT INTO MBOARD
VALUES(BNOSEQ.NEXTVAL, '테스트','테스트글입니다.','테스트테스트',SYSDATE);

SELECT *
FROM MBOARD;
