DROP SEQUENCE MNOSEQ;
DROP TABLE MEM;

CREATE SEQUENCE MNOSEQ;

CREATE TABLE MEM(
	MNO NUMBER PRIMARY KEY,
	MID VARCHAR2(500) NOT NULL,
	MPW VARCHAR2(500) NOT NULL,
	MNAME VARCHAR2(500) NOT NULL,
	MROLE VARCHAR2(500) NOT NULL,
	MENABLED VARCHAR2(2) NOT NULL,
	CONSTRAINT MROLE_ROLE_CK CHECK(MROLE IN ('ADMIN','USER')),
	CONSTRAINT MENABLED_ENABLED CHECK (MENABLED IN ('Y','N'))
);

INSERT INTO MEM
VALUES(MNOSEQ.NEXTVAL, 'user', 'user1234', '유저','USER','Y');

SELECT *
FROM MEM;