DROP SEQUENCE MNOSEQ;
DROP TABLE MEM;

CREATE SEQUENCE MNOSEQ;

CREATE TABLE MEM(
	MNO NUMBER PRIMARY KEY,
	MID VARCHAR2(500) NOT NULL,
	MPW VARCHAR2(500) NOT NULL,
	MNAME VARCHAR2(500) NOT NULL,
	AUTHORITY VARCHAR2(500) NOT NULL,
	ENABLED VARCHAR2(2) NOT NULL,
	CONSTRAINT MROLE_ROLE_CK CHECK(AUTHORITY IN ('ADMIN','USER')),
	CONSTRAINT MENABLED_ENABLED CHECK (ENABLED IN ('1','2'))
);
--'1'이 활성화

INSERT INTO MEM
VALUES(MNOSEQ.NEXTVAL, 'user', 'user1234', '유저','USER','1');

SELECT *
FROM MEM;