DROP TABLE CHAT;
DROP SEQUENCE CHAT_SEQ;

CREATE SEQUENCE CHAT_SEQ;
CREATE TABLE CHAT( -- STREAMING과 맞추는 것이 나을 것 같음 CHAT/STRAM OR CHATTING/STREAMING
CHAT_NO NUMBER NOT NULL,
	USER_ID VARCHAR2(500) NOT NULL,
	CHAT_TITLE VARCHAR2(1000) NOT NULL,
	CHAT_PUBLIC VARCHAR2(1000),
	CHAT_PASSWORD VARCHAR2(1000),
	CHAT_CLIENT NUMBER NOT NULL
	--CONSTRAINT CHAT_GN_FK FOREIGN KEY(GROUP_NO) REFERENCES GROUP_INFO(GROUP_NO),
	--CONSTRAINT CHAT_UI_FK FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID)
);

INSERT INTO CHAT VALUES(CHAT_SEQ.NEXTVAL, 2, 'DDD', 'DDD');
SELECT * FROM CHAT

DROP TABLE TEST;
DROP SEQUENCE TEST_SEQ;

CREATE SEQUENCE TEST_SEQ;
CREATE TABLE TEST( -- STREAMING과 맞추는 것이 나을 것 같음 CHAT/STRAM OR CHATTING/STREAMING
	CHAT_NO NUMBER NOT NULL,
	USER_ID VARCHAR2(500) NOT NULL,
	CHAT_TITLE VARCHAR2(1000) NOT NULL,
	CHAT_PUBLIC VARCHAR2(1000),
	CHAT_PASSWORD VARCHAR2(1000),
	CHAT_CLIENT NUMBER NOT NULL
);
INSERT INTO TEST VALUES(TEST_SEQ.NEXTVAL, 'dd','dd','공개','',0);	
INSERT INTO TEST VALUES(TEST_SEQ.NEXTVAL, '비밀번호','있는방','공개','ㅁㄴㅇㄹ',0);	
SELECT * FROM TEST

DELETE FROM FRIEND_LIST WHERE STATUS = 'SEND'
DELETE FROM FRIEND_LIST WHERE FRIEND_NO = 2 AND USER_NO = 3
SELECT * FROM FRIEND_LIST WHERE STATUS = 'SEND'
WHERE NAME = (SELECT * FROM TEST WHERE NAME = 'ㅇㅇㅇ')
