DROP TABLE CHAT;
DROP SEQUENCE CHAT_SEQ;
CREATE SEQUENCE CHAT_SEQ;
CREATE TABLE CHAT( -- STREAMING과 맞추는 것이 나을 것 같음 CHAT/STRAM OR CHATTING/STREAMING
	GROUP_NO NUMBER NOT NULL,
	USER_ID VARCHAR2(500) NOT NULL,
	CHAT_TITLE VARCHAR2(2000) NOT NULL,
	CHAT_CONTENT VARCHAR2(2000) NOT NULL
);

INSERT INTO CHAT VALUES(CHAT_SEQ.NEXTVAL, 2, 'DDD', 'DDD');
SELECT * FROM CHAT
DELETE FROM CHAT

DELETE FROM FRIEND_LIST WHERE STATUS = 'SEND'
DELETE FROM FRIEND_LIST WHERE FRIEND_NO = 2 AND USER_NO = 3
SELECT * FROM FRIEND_LIST WHERE STATUS = 'SEND'
WHERE NAME = (SELECT * FROM TEST WHERE NAME = 'ㅇㅇㅇ')

SELECT * FROM GROUP_INFO

DROP TABLE GROUP_INFO;
DROP SEQUENCE GROUP_INFO_SEQ;
CREATE SEQUENCE GROUP_INFO_SEQ;
CREATE TABLE GROUP_INFO(
	GROUP_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(2000) NOT NULL,
	USER_NAME VARCHAR2(2000) NOT NULL,
	GROUP_TITLE VARCHAR2(2000) UNIQUE,
	GROUP_CONTENT VARCHAR2(2000),
	GROUP_PUBLIC VARCHAR2(2000) DEFAULT '공개',
	GROUP_REGDATE DATE NOT NULL,
	GROUP_HASHTAG VARCHAR2(2000) NOT NULL,
	GROUP_SU NUMBER NOT NULL,
	GROUP_CLIENT NUMBER,
	GROUP_PW VARCHAR2(2000),
	GROUP_ANYONE VARCHAR2(100) NOT NULL,
	CONSTRAINT GROUP_ANY_CHK CHECK(GROUP_ANYONE IN ('Y','N')),
	CONSTRAINT GROUP_PUBLIC_CHK CHECK(GROUP_PUBLIC IN ('공개','비공개'))
);

DELETE FROM GROUP_INFO;

INSERT INTO GROUP_INFO VALUES	
(GROUP_INFO_SEQ.NEXTVAL, 'admin','관리자','공개방1','누구나 쓸 수 있는 방','공개',SYSDATE,'공개방1',10, 0,NULL,'Y');	

INSERT INTO GROUP_INFO VALUES
(GROUP_INFO_SEQ.NEXTVAL, 'user','유저','공개방2','누구나 쓸 수 있는 방','공개',SYSDATE,'공개방2',10, 0,NULL,'Y');	

INSERT INTO GROUP_INFO VALUES
(GROUP_INFO_SEQ.NEXTVAL, 'test','테스트1','공개방3','누구나 쓸 수 있는 방','공개',SYSDATE,'공개방2',10, 0,NULL,'Y');

INSERT INTO GROUP_INFO VALUES
(GROUP_INFO_SEQ.NEXTVAL, 'ming','밍','공개방4','누구나 쓸 수 있는 방','공개',SYSDATE,'공개방2',10, 0,NULL,'Y');

SELECT *
FROM GROUP_INFO
WHERE GROUP_TITLE = '공개방2' OR USER_ID = '공개방2'

SELECT ui.USER_NO, fl.FRIEND_NO, ui.USER_ID ,ui.USER_NAME,
	ui.USER_PHOTO, ui.USER_ACTIVE, fl.STATUS
	FROM FRIEND_LIST fl JOIN USER_INFO ui ON ui.USER_NO = fl.USER_NO(+)
	WHERE ui.USER_NAME = '테스트1'

	SELECT ui.USER_NO, fl.FRIEND_NO, ui.USER_ID ,ui.USER_NAME,
	ui.USER_PHOTO, ui.USER_ACTIVE, fl.STATUS
	FROM FRIEND_LIST fl JOIN USER_INFO ui ON ui.USER_NO = fl.USER_NO(+)
	WHERE (LOWER(ui.USER_NAME) LIKE LOWER( '%관%'))
	AND ui.USER_NAME NOT LIKE (
			SELECT USER_NAME
			FROM USER_INFO
			WHERE USER_NO = 1)
			
	DELETE 
	FROM USER_INFO 
	WHERE USER_NAME = '관리자2'		
			
INSERT INTO USER_INFO VALUES(USER_INFO_SEQ.NEXTVAL, 'admin2', 'admin2', 
'관리자2', 'tiwi.minibean@gmail.com', 'ADMIN', NULL, 'Y', 'admin2', SYSDATE);
	
	<!--이름이 포함된 -->
	
INSERT INTO USER_INFO VALUES(USER_INFO_SEQ.NEXTVAL, 'aaa', 'aaa', 
'관리자2', 'tiwi.minibean@gmai.com', 'ADMIN', NULL, 'Y', 'aaa', SYSDATE);
	
DELETE FROM USER_INFO WHERE USER_NAME = '관리자2'

INSERT INTO USER_INFO VALUES(USER_INFO_SEQ.NEXTVAL, 'omg', 'omg1234',
'밍','mingyeung@naver.com','USER',NULL,'Y', 'omg', SYSDATE);

DELETE FROM USER_INFO WHERE USER_ID = 'omg'

SELECT * FROM FRIEND_LIST;

DELETE FROM USER_INFO WHERE USER_NAME = '주명빈'

SELECT ui.USER_NAME, ui.USER_NO, ui.USER_ROLE, ui.USER_DISTINCT
		FROM USER_INFO ui
		WHERE USER_NO != 6
		AND LOWER(ui.USER_NAME) LIKE LOWER('%배민경%')
		AND USER_NO 
		NOT IN(
			SELECT fl.FRIEND_NO
			FROM FRIEND_LIST fl
			JOIN FRIEND_LIST fl2
			ON fl.FRIEND_NO = fl2.USER_NO
			AND fl.USER_NO = fl2.FRIEND_NO
			WHERE fl.USER_NO = 6)

