DROP TABLE CALBOARD;
DROP SEQUENCE CALBOARDSEQ;

CREATE SEQUENCE CALBOARDSEQ;
CREATE TABLE CALBOARD(

	CAL_NO NUMBER PRIMARY KEY,
	USER_NO NUMBER NOT NULL,
	CAL_TITLE VARCHAR2(2000) NOT NULL,
	CAL_CONTENT VARCHAR2(4000) NOT NULL,
	CAL_MDATE VARCHAR2(12) NOT NULL, 		--12자리로 만듬
	CAL_REGDATE DATE NOT NULL,
	CONSTRAINT CAL_UN_FK FOREIGN KEY(USER_NO) REFERENCES USER_INFO(USER_NO)
);

SELECT *
FROM CALBOARD;

INSERT INTO CALBOARD
VALUES(CALBOARDSEQ.NEXTVAL,'1','풀업 챌린지','15개 10세트 도전','20201113',SYSDATE);